// Generated by BUCKLESCRIPT VERSION 4.0.7, PLEASE EDIT WITH CARE

import * as ReactDOMRe from "reason-react/src/ReactDOMRe.js";
import * as ReasonReact from "reason-react/src/ReasonReact.js";
import * as Home$ReactTemplate from "./pages/Home.bs.js";

ReactDOMRe.renderToElementWithId(ReasonReact.element(undefined, undefined, Home$ReactTemplate.make(/* array */[])), "index");

export {
  
}
/*  Not a pure module */
